name: time_of_day_widget
description: A widget that changes state over TimeOfDay.
version: 1.0.0+1
repository: https://github.com/rocaforarnelo/time-of-day-widget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true